/**
 * Audit actions tracked in MediDesk.
 */
export const AuditAction = {
  SYSTEM_INITIALIZED: 'SYSTEM_INITIALIZED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DISABLED: 'USER_DISABLED',
  ROLE_ASSIGNED: 'ROLE_ASSIGNED',
  DATABASE_MIGRATED: 'DATABASE_MIGRATED',

  // Backup & Restore Actions
  BACKUP_STARTED: 'BACKUP_STARTED',
  BACKUP_CREATED: 'BACKUP_CREATED',
  LOCAL_BACKUP_COMPLETED: 'LOCAL_BACKUP_COMPLETED',
  LOCAL_BACKUP_FAILED: 'LOCAL_BACKUP_FAILED',
  CLOUD_BACKUP_QUEUED: 'CLOUD_BACKUP_QUEUED',
  CLOUD_BACKUP_STARTED: 'CLOUD_BACKUP_STARTED',
  CLOUD_BACKUP_COMPLETED: 'CLOUD_BACKUP_COMPLETED',
  CLOUD_BACKUP_FAILED: 'CLOUD_BACKUP_FAILED',
  BACKUP_VERIFIED: 'BACKUP_VERIFIED',
  RESTORE_STARTED: 'RESTORE_STARTED',
  BACKUP_RESTORED: 'BACKUP_RESTORED',
  RESTORE_COMPLETED: 'RESTORE_COMPLETED',
  RESTORE_FAILED: 'RESTORE_FAILED',

  LICENSE_VERIFIED: 'LICENSE_VERIFIED',
  LICENSE_ACTIVATED: 'LICENSE_ACTIVATED',
  LICENSE_TRIAL_INITIALIZED: 'LICENSE_TRIAL_INITIALIZED',
  DIAGNOSTICS_EXECUTED: 'DIAGNOSTICS_EXECUTED',
  PRINTER_CONFIGURED: 'PRINTER_CONFIGURED',
  DOCUMENT_PRINTED: 'DOCUMENT_PRINTED',

  // Phase 3 Actions
  PATIENT_CREATED: 'PATIENT_CREATED',
  PATIENT_UPDATED: 'PATIENT_UPDATED',
  PATIENT_DUPLICATE_WARNING: 'PATIENT_DUPLICATE_WARNING',
  DOCTOR_CREATED: 'DOCTOR_CREATED',
  DOCTOR_UPDATED: 'DOCTOR_UPDATED',
  DOCTOR_DEACTIVATED: 'DOCTOR_DEACTIVATED',
  APPOINTMENT_CREATED: 'APPOINTMENT_CREATED',
  APPOINTMENT_UPDATED: 'APPOINTMENT_UPDATED',
  APPOINTMENT_CANCELLED: 'APPOINTMENT_CANCELLED',
  APPOINTMENT_CHECKED_IN: 'APPOINTMENT_CHECKED_IN',
  APPOINTMENT_STATUS_CHANGED: 'APPOINTMENT_STATUS_CHANGED',

  // Phase 4 Clinical Actions
  VISIT_CREATED: 'VISIT_CREATED',
  VISIT_UPDATED: 'VISIT_UPDATED',
  VISIT_COMPLETED: 'VISIT_COMPLETED',
  VISIT_CANCELLED: 'VISIT_CANCELLED',
  VITALS_CREATED: 'VITALS_CREATED',
  VITALS_UPDATED: 'VITALS_UPDATED',
  ALLERGY_CREATED: 'ALLERGY_CREATED',
  ALLERGY_UPDATED: 'ALLERGY_UPDATED',
  ALLERGY_STATUS_CHANGED: 'ALLERGY_STATUS_CHANGED',
  MEDICAL_HISTORY_CREATED: 'MEDICAL_HISTORY_CREATED',
  MEDICAL_HISTORY_UPDATED: 'MEDICAL_HISTORY_UPDATED',
  DIAGNOSIS_CREATED: 'DIAGNOSIS_CREATED',
  DIAGNOSIS_UPDATED: 'DIAGNOSIS_UPDATED',
  PRESCRIPTION_CREATED: 'PRESCRIPTION_CREATED',
  PRESCRIPTION_SIGNED: 'PRESCRIPTION_SIGNED',
  PRESCRIPTION_VERSION_CREATED: 'PRESCRIPTION_VERSION_CREATED',
  PRESCRIPTION_CANCELLED: 'PRESCRIPTION_CANCELLED',
  PRESCRIPTION_SUPERSEDED: 'PRESCRIPTION_SUPERSEDED',
  FOLLOWUP_CREATED: 'FOLLOWUP_CREATED',
  FOLLOWUP_UPDATED: 'FOLLOWUP_UPDATED',
  CLINICAL_CORRECTION_REQUESTED: 'CLINICAL_CORRECTION_REQUESTED',
  CLINICAL_CORRECTION_APPLIED: 'CLINICAL_CORRECTION_APPLIED',
  CLINICAL_CORRECTION_APPROVED: 'CLINICAL_CORRECTION_APPROVED',
  CLINICAL_CORRECTION_REJECTED: 'CLINICAL_CORRECTION_REJECTED',

  // Phase 5 Pharmacy Actions
  MEDICINE_CREATED: 'MEDICINE_CREATED',
  MEDICINE_UPDATED: 'MEDICINE_UPDATED',
  MEDICINE_DEACTIVATED: 'MEDICINE_DEACTIVATED',
  SUPPLIER_CREATED: 'SUPPLIER_CREATED',
  SUPPLIER_UPDATED: 'SUPPLIER_UPDATED',
  PURCHASE_CREATED: 'PURCHASE_CREATED',
  PURCHASE_CANCELLED: 'PURCHASE_CANCELLED',
  STOCK_ADJUSTED: 'STOCK_ADJUSTED',
  BATCH_CREATED: 'BATCH_CREATED',
  BATCH_UPDATED: 'BATCH_UPDATED',
  SALE_CREATED: 'SALE_CREATED',
  SALE_CANCELLED: 'SALE_CANCELLED',
  SALE_RETURN_CREATED: 'SALE_RETURN_CREATED',
  TAX_RULE_CREATED: 'TAX_RULE_CREATED',
  TAX_RULE_UPDATED: 'TAX_RULE_UPDATED',

  // Phase 7 LAN & Multi-Computer Actions
  LAN_SERVER_STARTED: 'LAN_SERVER_STARTED',
  LAN_SERVER_STOPPED: 'LAN_SERVER_STOPPED',
  LAN_DEVICE_REGISTERED: 'LAN_DEVICE_REGISTERED',
  LAN_DEVICE_APPROVED: 'LAN_DEVICE_APPROVED',
  LAN_DEVICE_REVOKED: 'LAN_DEVICE_REVOKED',
  LAN_DEVICE_BLOCKED: 'LAN_DEVICE_BLOCKED',
  LAN_PAIRING_PIN_GENERATED: 'LAN_PAIRING_PIN_GENERATED'
} as const;

export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction];

export const AuditResult = {
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
  DENIED: 'DENIED'
} as const;

export type AuditResult = (typeof AuditResult)[keyof typeof AuditResult];
